version: '2'
services:
  proxy:
    image: 'zhaishuaigan/nginx-proxy'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    ports:
      - '80:80'
  home:
    image: zhaishuaigan/php:tp6
    volumes:
      - "/data:/app"
    environment:
      - VIRTUAL_HOST=demo.com