Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.box_url = "http://fetch.ngapp.net/vagrant/xenial-server-amd64.box.box"
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
    end
    # config.ssh.username = "root"
    # config.ssh.password = "root"
    # config.vm.network "forwarded_port", guest: 80, host: 80
    # config.vm.network "forwarded_port", guest: 3306, host: 3306
    config.vm.network "private_network", ip: "10.0.0.11"
    config.vm.synced_folder "../", "/data"
    config.vm.provision "shell", inline: <<-SHELL
        
        # 启动后直接切换到root用户
        echo 'sudo su root' >> /home/vagrant/.bashrc
        echo 'cd /data' >> /root/.bashrc

        echo 'if [ ! -f /data/docker/install.lock ]; then' >> /root/.bashrc
        echo '    source /data/docker/install.sh' >> /root/.bashrc
        echo 'fi' >> /root/.bashrc
        
    SHELL
end